name: Audit

on: [push]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ hashFiles('**/yarn.lock') }}
      # - name: Audit dependencies
      #   run: yarn audit
