name: Build/release

on: [pull_request]

env:
  GITHUB_SHA: ${{ github.sha }}

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            NPM_COMMAND: mac

          - os: ubuntu-latest
            NPM_COMMAND: linux

          - os: windows-latest
            NPM_COMMAND: win

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - run: echo ${{ github.sha }}

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install package
        run: yarn

      - run: echo ${{ matrix.NPM_COMMAND }}

      - name: Build releases
        run: yarn package-${{ matrix.NPM_COMMAND }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2
        name: Upload Windows build
        if: matrix.os == 'windows-latest'
        with:
          name: stacks-wallet-windows
          path: |
            release/**/*.exe
            release/**/*.msi

      - uses: actions/upload-artifact@v2
        name: Upload MacOS build
        if: matrix.os == 'macos-latest'
        with:
          name: stacks-wallet-macos
          path: release/**/*.dmg

      - uses: actions/upload-artifact@v2
        name: Upload Linux build
        if: matrix.os == 'ubuntu-latest'
        with:
          name: stacks-wallet-linux
          path: |
            release/**/*.deb
            release/**/*.rpm
