name: Debug build

on: [pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        stx_network: [testnet, mainnet]
        include:
          - os: macos-latest
            NPM_COMMAND: mac
            CSC_LINK_SECRET_NAME: CODE_SIGNING_CERTIFICATE_APPLE
            CSC_KEY_PASSWORD_SECRET_NAME: CODE_SIGNING_PASSWORD_APPLE

          - os: ubuntu-latest
            NPM_COMMAND: linux

          - os: windows-latest
            NPM_COMMAND: win
            CSC_LINK_SECRET_NAME: CODE_SIGNING_CERTIFICATE_WINDOWS
            CSC_KEY_PASSWORD_SECRET_NAME: CODE_SIGNING_PASSWORD_WINDOWS

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - name: Print environment variables
        run: |
          echo "GITHUB_REPOSITORY_SLUG=$GITHUB_REPOSITORY_SLUG"
          echo "GITHUB_REPOSITORY_OWNER=$GITHUB_REPOSITORY_OWNER"
          echo "GITHUB_REPOSITORY_OWNER_SLUG=$GITHUB_REPOSITORY_OWNER_SLUG"
          echo "GITHUB_REPOSITORY_NAME=$GITHUB_REPOSITORY_NAME"
          echo "GITHUB_REPOSITORY_NAME_SLUG=$GITHUB_REPOSITORY_NAME_SLUG"
          echo "GITHUB_REF_SLUG=$GITHUB_REF_SLUG"
          echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
          echo "GITHUB_REF_NAME_SLUG=$GITHUB_REF_NAME_SLUG"
          echo "GITHUB_SHA_SHORT=$GITHUB_SHA_SHORT"
          echo "GITHUB_SHA=$GITHUB_SHA"

      - name: Variables
        id: vars
        run: |
          echo "::set-output name=version::$(cat package.json | jq -r .version)"
          echo "::set-output name=branch_name::$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=pull_request_id::$(echo $GITHUB_REF)"

      - name: Install code-signing certs - Apple only
        uses: apple-actions/import-codesign-certs@v1
        if: matrix.os == 'macos-latest'
        with:
          p12-file-base64: ${{ secrets.CODE_SIGNING_CERTIFICATE_APPLE }}
          p12-password: ${{ secrets.CODE_SIGNING_PASSWORD_APPLE }}

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      #
      # Windows build breaks when using the package.json script to install `app/` packages
      # using separate run to install those packages separately
      - name: Install packages
        run: yarn --frozen-lockfile --ignore-scripts
        env:
          STX_NETWORK: ${{ matrix.stx_network }}

      - name: Install `app/` packages
        run: cd app && yarn --frozen-lockfile --ignore-scripts
        env:
          STX_NETWORK: ${{ matrix.stx_network }}

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6

      - name: Build releases
        run: ./node_modules/.bin/cross-env DEBUG_PROD=true yarn package-${{ matrix.NPM_COMMAND }}
        env:
          SHA: ${{ github.event.pull_request.head.sha }}
          NODE_ENV: production
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WALLET_VERSION: ${{ steps.extract_version.outputs.version }}
          PULL_REQUEST: ${{ steps.vars.outputs.pull_request_id }}
          BRANCH_NAME: ${{ steps.vars.outputs.branch_name }}
          STX_NETWORK: ${{ matrix.stx_network }}
          CSC_LINK: ${{ secrets[matrix.CSC_LINK_SECRET_NAME] }}
          CSC_KEY_PASSWORD: ${{ secrets[matrix.CSC_KEY_PASSWORD_SECRET_NAME] }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}

      - run: ls -R release

      - uses: actions/upload-artifact@v2
        name: Upload Windows builds
        if: matrix.os == 'windows-latest'
        with:
          name: stacks-wallet-${{ steps.vars.outputs.version }}-${{ matrix.stx_network }}-windows
          path: |
            release/**/*.exe
            release/**/*.msi
      - uses: actions/upload-artifact@v2
        name: Upload MacOS builds
        if: matrix.os == 'macos-latest'
        with:
          name: stacks-wallet-${{ steps.vars.outputs.version }}-${{ matrix.stx_network }}-macos
          path: release/**/*.dmg

      - uses: actions/upload-artifact@v2
        name: Upload Linux builds
        if: matrix.os == 'ubuntu-latest'
        with:
          name: stacks-wallet-${{ steps.vars.outputs.version }}-${{ matrix.stx_network }}-linux
          path: |
            release/**/*.deb
            release/**/*.rpm

      - uses: lucasmotta/pull-request-sticky-header@1.0.0
        if: (!contains(needs.*.result, 'failure'))
        with:
          header: '> [Download the latest build](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Remove header if build failed
      - uses: lucasmotta/pull-request-sticky-header@1.0.0
        if: (contains(needs.*.result, 'failure'))
        with:
          header: '> _Build failed, [see here for details](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})_'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
