name: Exact versions

on: [push]

jobs:
  check-versions:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - run: yarn add -ED @actions/core

      - name: Check exact versions
        uses: ./.github/actions/check-version-lock
