name: Typecheck

on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - run: sudo apt-get install libusb-1.0-0-dev

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn
        env:
          STX_NETWORK: testnet

      - name: Build
        run: yarn tsc --noEmit
