name: Typecheck

on:
  push:
    branches:
      - '**'
jobs:
  typecheck:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - run: sudo apt-get install libusb-1.0-0-dev libudev-dev

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 240
          max_attempts: 3
          retry_on: error
          command: yarn
        env:
          STX_NETWORK: testnet

      - name: Check types
        run: yarn tsc --noEmit
